services:
  mysql-server:
    image: mysql:8
    container_name: mysql-server
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: boot-admin
      TZ: Asia/Shanghai
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 5s
      timeout: 10s
      retries: 10
  redis-server:
    image: redis:7
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
