version: '3'
services:
  mysql8_server:
    image: mysql:8
    container_name: boot_admin_mysql8_server
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: boot-admin
      TZ: Asia/Shanghai
  redis_server:
    image: redis:alpine
    container_name: boot_admin_redis_server
    ports:
      - 6379:6379
    volumes:
      # redis配置
      - ./conf/redis:/usr/local/etc/redis
      # redis 数据挂载
      - ./data/redis:/data
    command: redis-server /usr/local/etc/redis/redis.conf

