# app service
boot-admin-rpc.services[sys].name=boot-admin-sys
boot-admin-rpc.services[sys].address=boot_admin_app:12200
# job service
boot-admin-rpc.services[job].name=boot-admin-sys
boot-admin-rpc.services[job].address=boot_admin_job:12201