# app service
boot-admin-rpc.services[sys].name=boot-admin-sys
boot-admin-rpc.services[sys].address=127.0.0.1:12200
# job service
boot-admin-rpc.services[job].name=boot-admin-sys
boot-admin-rpc.services[job].address=127.0.0.1:12201