<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.hb0730</groupId>
        <artifactId>commons</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>common-security</artifactId>
    <description>Spring Security相关配置</description>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>


    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-security</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-redis</artifactId>
        </dependency>
        <dependency>
            <groupId>com.auth0</groupId>
            <artifactId>java-jwt</artifactId>
        </dependency>

        <!--mapstruct-->
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct</artifactId>
        </dependency>


        <dependency>
            <groupId>com.hb0730</groupId>
            <artifactId>common-base</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>com.hb0730</groupId>
            <artifactId>common-cache</artifactId>
            <version>${revision}</version>
        </dependency>
        <dependency>
            <groupId>com.hb0730</groupId>
            <artifactId>common-mybatis-tenant</artifactId>
            <version>${revision}</version>
        </dependency>

    </dependencies>

</project>