server:
  port: 9001

logging:
  level:
    root: info
    com.hb0730: debug

spring:
  application:
    name: boot-admin-app
    version: 1.0.0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/boot-admin?useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: true
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456
      database: 0

sofa:
  boot:
    rpc:
      registry-address: local://${user.home}/.sofa-boot/registry/boot-admin.reg
      enable-auto-publish: true
      bolt-port: 12200

