server:
  port: 9005


logging:
  level:
    root: info
    com.hb0730: debug

spring:
  application:
    name: boot-admin-api
    version: 1.0.0
  data:
    redis:
      host: localhost
      port: 6379
      password: 123456
      database: 0
sofa:
  boot:
    rpc:
      registry-address: local://${user.home}/.sofa-boot/registry/boot-admin.reg

